// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.CaptivePortalDataService;

#nullable disable

namespace Services.Migrations
{
    [DbContext(typeof(CaptivePortalDbContext))]
    [Migration("20241111050455_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Services.CaptivePortalProfileJobService.GuestProfileJob", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobFrequencyInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JobScheduledAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("GuestProfileJobs", (string)null);
                });

            modelBuilder.Entity("Services.CaptivePortalProfileJobService.GuestProfileJobResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailValid")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("GuestProfileJobResults", (string)null);
                });

            modelBuilder.Entity("Services.CaptivePortalProfileService.GuestProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("GuestProfiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
